import Head from 'next/head';
import Spline from '@splinetool/react-spline';
export default function Home() {
  return (
    <div>
      <Head>
        <title>create-permaweb-app</title>
        <meta name="description" content="Generated by npx create-permaweb-app" />
        <link rel="icon" href="/cpa.ico" />
      </Head>
      <div>
        <div className="main">
          <div className="content">
            <Spline className="animation" scene="https://prod.spline.design/XLnDWYFfWJOD4Qlq/scene.splinecode" />
            <div className="overlay">
              <img src="https://arweave.net/IWZM05IXemJ3vhKYjHfADhw-v8rw8sS2i39mVCbp-rQ" alt="Logo" />
              <p><a href="https://create-permaweb-app.arweave.dev" target="_blank">Get Started</a></p>
              <a href="https://cookbook.arweave.dev" target="_blank">Explore the Arweave Cookbook</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}