import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>create-permaweb-app App</title>
        <meta name="description" content="Generated by npx create-permaweb-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main">
        <div className="content">
          <img src="/cpa.svg" alt="Logo" />
          <p>Edit, save and reload</p>
          <a href="https://cookbook.arweave.dev" target="_blank">Learn more how to build</a>
        </div>
      </div>
    </div>
  );
};
